apiVersion: v1
kind: Template
metadata:
  name: image-manager-sa-template
  annotations:
    openshift.io/display-name: Service Acount Template
    description: Template to create a service account
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "${SERVICE_ACCOUNT_NAME}"
    namespace: "${NAMESPACE}"
- apiVersion: v1
  kind: ClusterRoleBinding
  metadata:
    name: ${ROLE_NAME}
  roleRef:
    name: ${ROLE_NAME}
  subjects:
  - kind: ServiceAccount
    name: "${SERVICE_ACCOUNT_NAME}"
    namespace: ${NAMESPACE}
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: ${ROLE_NAME}
  rules:
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - serviceaccounts
    verbs:
    - get
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - secrets
    verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    - image.openshift.io
    attributeRestrictions: null
    resources:
    - imagestreamimages
    - imagestreamtags
    - imagestreams
    - images
    verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    - image.openshift.io
    attributeRestrictions: null
    resources:
    - imagestreamimports
    - imagesignatures
    verbs:
    - create
  - apiGroups:
    - ""
    - image.openshift.io
    attributeRestrictions: null
    resources:
    - imagestreams/layers
    verbs:
    - get
    - update
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - pods
    verbs:
    - create
    - get
    - list
    - watch
    - delete
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - pods/proxy
    verbs:
    - get
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - images
    verbs:
    - create
    - get
  - apiGroups:
    - ""
    - "cop.redhat.com"
    attributeRestrictions: null
    resources:
    - imagesigningrequests
    - imagescanningrequests
    verbs:
    - get
    - list
    - update
    - watch
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: ${IMAGE_SCANNING_SIGNING_ROLE_NAME}
  rules:
  - apiGroups:
    - ""
    - "cop.redhat.com"
    attributeRestrictions: null
    resources:
    - imagesigningrequests
    - imagescanningrequests
    verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
parameters:
- name: SERVICE_ACCOUNT_NAME
  displayName: Service Account Name
  description: Name of the service account to Create
  value: imagemanager
  required: true
- name: ROLE_NAME
  displayName: Role Name
  description: Name of the role resources
  value: image-management
  required: true
- name: IMAGE_SCANNING_SIGNING_ROLE_NAME
  displayName: Image Signing Scanning Role Name
  description: Name of the image scanning and signing role
  value: image-scanning-signing-resources
- name: NAMESPACE
  displayName: Namespace
  description: Namespace Containing Resources
  value: image-management
  required: true
