apiVersion: v1
kind: Template
metadata:
  name: image-signing-scanning-pipeline-build
  annotations:
    openshift.io/display-name: Image Scanning/Signing Builds
    description: Template to create an build artifacts for Image Scanning and Signing application
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APPLICATION_NAME}
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: "${APPLICATION_NAME}-pipeline"
  spec:
    source:
      type: Git
      git:
        uri: ${PIPELINE_REPOSITORY_URL}
        ref: ${PIPELINE_REPOSITORY_REF}
    triggers:
    - type: "ConfigChange"
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: ${PIPELINE_SCRIPT}
        env:
        - name: SOURCE_CODE_URL
          value: ${SOURCE_CODE_URL}
        - name: SOURCE_CODE_REF
          value: ${SOURCE_CODE_REF}
        - name: BUILD_APP_TAG
          value: ${BUILD_APP_TAG}
        - name: DEPLOY_APP_TAG
          value: ${DEPLOY_APP_TAG}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ${FROM_IMAGE}
          namespace: ${FROM_IMAGE_NAMESPACE}
      type: Source
parameters:
- name: APPLICATION_NAME
  displayName: Application Name
  description: Name of the Application
  value: example-application
  required: true
- description: Image stream tag for the image you'd like to use to build the application
  name: FROM_IMAGE
  required: true
  value: redhat-openjdk18-openshift:1.2
- description: Namespace for the Image
  name: FROM_IMAGE_NAMESPACE
  required: true
  value: openshift
- description: Git source URI for application
  name: PIPELINE_REPOSITORY_URL
  required: true
  value: https://github.com/akram/image-scanning-signing-service.git
- description: Git branch/tag reference
  name: PIPELINE_REPOSITORY_REF
  value: "master"
- description: Path within Git project pointing to the pipeline run script
  name: PIPELINE_SCRIPT
  value: ci/Jenkinsfile
- description: Git source URI for application
  name: SOURCE_CODE_URL
  required: true
  value: https://github.com/redhat-cop/spring-rest.git
- description: Git branch/tag reference
  name: SOURCE_CODE_REF
  value: "master"
- description: Tag reference used for deployment
  displayName: Deploy tag
  name: DEPLOY_APP_TAG
  required: true
  value: deploy
- description: Tag reference used for the result of the build
  displayName: Build tag
  name: BUILD_APP_TAG
  required: true
  value: latest
