/*
Copyright 2018 The Red Hat Container and PaaS Community of Practice.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	cop_redhat_com_v1alpha1 "github.com/redhat-cop/image-scanning-signing-service/pkg/apis/cop.redhat.com/v1alpha1"
	versioned "github.com/redhat-cop/image-scanning-signing-service/pkg/client/clientset/versioned"
	internalinterfaces "github.com/redhat-cop/image-scanning-signing-service/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/redhat-cop/image-scanning-signing-service/pkg/client/listers/cop/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// ImageSigningRequestInformer provides access to a shared informer and lister for
// ImageSigningRequests.
type ImageSigningRequestInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ImageSigningRequestLister
}

type imageSigningRequestInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewImageSigningRequestInformer constructs a new informer for ImageSigningRequest type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewImageSigningRequestInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.CopV1alpha1().ImageSigningRequests(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.CopV1alpha1().ImageSigningRequests(namespace).Watch(options)
			},
		},
		&cop_redhat_com_v1alpha1.ImageSigningRequest{},
		resyncPeriod,
		indexers,
	)
}

func defaultImageSigningRequestInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewImageSigningRequestInformer(client, v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *imageSigningRequestInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cop_redhat_com_v1alpha1.ImageSigningRequest{}, defaultImageSigningRequestInformer)
}

func (f *imageSigningRequestInformer) Lister() v1alpha1.ImageSigningRequestLister {
	return v1alpha1.NewImageSigningRequestLister(f.Informer().GetIndexer())
}
