apiVersion: v1
kind: Template
metadata:
  name: s2i-golang
  annotations:
    openshift.io/display-name: S2I Golang Builder
    description: Template to create a Source-To-Image Builder for Golang
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    source:
      contextDir: "${CONTEXT_DIR}"
      git:
        ref: "${SOURCE_REPOSITORY_REF}"
        uri: "${SOURCE_REPOSITORY_URL}"
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ${FROM_IMAGE}
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
parameters:
- name: NAME
  displayName: Name
  description: Name Applied to the Resulting ImageStream and BuildConfig
  value: s2i-golang
  required: true
- description: Image stream tag for the image you'd like to use to build the application
  name: FROM_IMAGE
  required: true
  value: rhel7:7.4
- description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
  value: master
- description: Git source URL for application
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/akram/image-scanning-signing-service
- description: Path within Git repository to build; empty for root of repository
  name: CONTEXT_DIR
  value: images/s2i-golang
