#!/bin/bash -e
cat <<EOF
This is the s2i-golang S2I image:
To use it, install S2I: https://github.com/openshift/source-to-image

Sample invocation:

s2i build git://<source code> s2i-golang <application image>

You can then run the resulting image via:
docker run <application image>

Or if you have application arguments:
docker run -e "ARGS=-goarg1=goval1 -goarg2=goval2"

EOF