name: image-signer
on:
  push:
    paths:
      - "deploy/centos/signing-image/**"
    tags:
      - "*"
  pull_request:
    paths:
      - "deploy/centos/signing-image/**"
jobs:
  build_push:
    name: "Singing Image"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: |
          # Version is based on a semantic version tag
          VERSION=${GITHUB_REF#refs/tags/}
          # Publish to latest, minor, and patch tags
          TAGS=('latest')
          # Add Tag is Exists
          if [ "$VERSION" != "$GITHUB_REF" ]; then
            TAGS=('latest' "${VERSION}")
          fi
          # Set IMAGE_TAGS output for use in next step
          ( IFS=$','; echo "::set-output name=IMAGE_TAGS::${TAGS[*]}" )
      - name: "Build and Push Image"
        uses: docker/build-push-action@v1
        with:
          path: deploy/centos/signing-image
          username: ${{ secrets.SIGNER_REGISTRY_USERNAME }}
          password: ${{ secrets.SIGNER_REGISTRY_PASSWORD }}
          registry: ${{ secrets.SIGNER_REGISTRY_SERVER }}
          repository: ${{ secrets.SIGNER_REGISTRY_REPOSITORY }}
          push: ${{ (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) && secrets.OPERATOR_REGISTRY_PUSH == 'true'  }}
          tags: "${{ steps.get_version.outputs.IMAGE_TAGS }}"
